# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Qdevice
version: "1.0.0"
slug: qdevice
description: Corosync-qdevice
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  5403/tcp: 5403
